const SLIDER_ICON_TRANSLATE_OFFSET = 20;
const SLIDER_MARKER_ICON_SIZE = 50;
const SLIDER_SECTION_TRANSLATE_OFFSET = 3;

export {
	SLIDER_ICON_TRANSLATE_OFFSET,
	SLIDER_MARKER_ICON_SIZE,
	SLIDER_SECTION_TRANSLATE_OFFSET,
};
