const MINIFY_TWICE_COEFFICIENT = 0.5;
const MAX_SCORE = 10;
const ANIMATION_TIME = 1000;
const ANIMATION_REPETITIONS = 1;
const REPETITION_STEP = 1;

export {
	ANIMATION_REPETITIONS,
	ANIMATION_TIME,
	MAX_SCORE,
	MINIFY_TWICE_COEFFICIENT,
	REPETITION_STEP,
};
