const LoadingSetting = {
	INITIAL_PERCENT: 0,
	MAX_PERCENT: 100,
	PERCENT_DECIMALS_LENGTH: 0,
	PROCESSING_STAGE_LENGTH: 1000,
	PROCESSING_TIME_FINISH: 8000,
	WHEEL_SIZE: 250,
} as const;

export { LoadingSetting };
