import { SPACINGS } from "~/libs/styles/global-styles/spacings";

const MARGINS = {
	m2: { margin: SPACINGS.xxxs },
	m4: { margin: SPACINGS.xxs },
	m8: { margin: SPACINGS.xs },
	m12: { margin: SPACINGS.sm },
	m16: { margin: SPACINGS.md },
	m24: { margin: SPACINGS.lg },
	m32: { margin: SPACINGS.xl },
	m48: { margin: SPACINGS.xxl },

	mb2: { marginBottom: SPACINGS.xxxs },
	mb4: { marginBottom: SPACINGS.xxs },
	mb8: { marginBottom: SPACINGS.xs },
	mb12: { marginBottom: SPACINGS.sm },
	mb16: { marginBottom: SPACINGS.md },
	mb24: { marginBottom: SPACINGS.lg },
	mb32: { marginBottom: SPACINGS.xl },
	mb48: { marginBottom: SPACINGS.xxl },

	mh2: { marginHorizontal: SPACINGS.xxxs },
	mh4: { marginHorizontal: SPACINGS.xxs },
	mh8: { marginHorizontal: SPACINGS.xs },
	mh12: { marginHorizontal: SPACINGS.sm },
	mh16: { marginHorizontal: SPACINGS.md },
	mh24: { marginHorizontal: SPACINGS.lg },
	mh32: { marginHorizontal: SPACINGS.xl },
	mh48: { marginHorizontal: SPACINGS.xxl },

	ml2: { marginLeft: SPACINGS.xxxs },
	ml4: { marginLeft: SPACINGS.xxs },
	ml8: { marginLeft: SPACINGS.xs },
	ml12: { marginLeft: SPACINGS.sm },
	ml16: { marginLeft: SPACINGS.md },
	ml24: { marginLeft: SPACINGS.lg },
	ml32: { marginLeft: SPACINGS.xl },
	ml48: { marginLeft: SPACINGS.xxl },

	mr2: { marginRight: SPACINGS.xxxs },
	mr4: { marginRight: SPACINGS.xxs },
	mr8: { marginRight: SPACINGS.xs },
	mr12: { marginRight: SPACINGS.sm },
	mr16: { marginRight: SPACINGS.md },
	mr24: { marginRight: SPACINGS.lg },
	mr32: { marginRight: SPACINGS.xl },
	mr48: { marginRight: SPACINGS.xxl },

	mt2: { marginTop: SPACINGS.xxxs },
	mt4: { marginTop: SPACINGS.xxs },
	mt8: { marginTop: SPACINGS.xs },
	mt12: { marginTop: SPACINGS.sm },
	mt16: { marginTop: SPACINGS.md },
	mt24: { marginTop: SPACINGS.lg },
	mt32: { marginTop: SPACINGS.xl },
	mt48: { marginTop: SPACINGS.xxl },

	mv2: { marginVertical: SPACINGS.xxxs },
	mv4: { marginVertical: SPACINGS.xxs },
	mv8: { marginVertical: SPACINGS.xs },
	mv12: { marginVertical: SPACINGS.sm },
	mv16: { marginVertical: SPACINGS.md },
	mv24: { marginVertical: SPACINGS.lg },
	mv32: { marginVertical: SPACINGS.xl },
	mv48: { marginVertical: SPACINGS.xxl },
};

export { MARGINS };
