import { SPACING } from "~/libs/styles/global-styles/spacing";

const MARGINS = {
	m2: { margin: SPACING.xxxs },
	m4: { margin: SPACING.xxs },
	m8: { margin: SPACING.xs },
	m12: { margin: SPACING.sm },
	m16: { margin: SPACING.md },
	m24: { margin: SPACING.lg },
	m32: { margin: SPACING.xl },
	m48: { margin: SPACING.xxl },

	mb2: { marginBottom: SPACING.xxxs },
	mb4: { marginBottom: SPACING.xxs },
	mb8: { marginBottom: SPACING.xs },
	mb12: { marginBottom: SPACING.sm },
	mb16: { marginBottom: SPACING.md },
	mb24: { marginBottom: SPACING.lg },
	mb32: { marginBottom: SPACING.xl },
	mb48: { marginBottom: SPACING.xxl },

	mh2: { marginHorizontal: SPACING.xxxs },
	mh4: { marginHorizontal: SPACING.xxs },
	mh8: { marginHorizontal: SPACING.xs },
	mh12: { marginHorizontal: SPACING.sm },
	mh16: { marginHorizontal: SPACING.md },
	mh24: { marginHorizontal: SPACING.lg },
	mh32: { marginHorizontal: SPACING.xl },
	mh48: { marginHorizontal: SPACING.xxl },

	ml2: { marginLeft: SPACING.xxxs },
	ml4: { marginLeft: SPACING.xxs },
	ml8: { marginLeft: SPACING.xs },
	ml12: { marginLeft: SPACING.sm },
	ml16: { marginLeft: SPACING.md },
	ml24: { marginLeft: SPACING.lg },
	ml32: { marginLeft: SPACING.xl },
	ml48: { marginLeft: SPACING.xxl },

	mr2: { marginRight: SPACING.xxxs },
	mr4: { marginRight: SPACING.xxs },
	mr8: { marginRight: SPACING.xs },
	mr12: { marginRight: SPACING.sm },
	mr16: { marginRight: SPACING.md },
	mr24: { marginRight: SPACING.lg },
	mr32: { marginRight: SPACING.xl },
	mr48: { marginRight: SPACING.xxl },

	mt2: { marginTop: SPACING.xxxs },
	mt4: { marginTop: SPACING.xxs },
	mt8: { marginTop: SPACING.xs },
	mt12: { marginTop: SPACING.sm },
	mt16: { marginTop: SPACING.md },
	mt24: { marginTop: SPACING.lg },
	mt32: { marginTop: SPACING.xl },
	mt48: { marginTop: SPACING.xxl },

	mv2: { marginVertical: SPACING.xxxs },
	mv4: { marginVertical: SPACING.xxs },
	mv8: { marginVertical: SPACING.xs },
	mv12: { marginVertical: SPACING.sm },
	mv16: { marginVertical: SPACING.md },
	mv24: { marginVertical: SPACING.lg },
	mv32: { marginVertical: SPACING.xl },
	mv48: { marginVertical: SPACING.xxl },
};

export { MARGINS };
