import { SPACINGS } from "~/libs/styles/global-styles/spacings";

const PADDINGS = {
	p2: { padding: SPACINGS.xxxs },
	p4: { padding: SPACINGS.xxs },
	p8: { padding: SPACINGS.xs },
	p12: { padding: SPACINGS.sm },
	p16: { padding: SPACINGS.md },
	p24: { padding: SPACINGS.lg },
	p32: { padding: SPACINGS.xl },
	p48: { padding: SPACINGS.xxl },

	pb2: { paddingBottom: SPACINGS.xxxs },
	pb4: { paddingBottom: SPACINGS.xxs },
	pb8: { paddingBottom: SPACINGS.xs },
	pb12: { paddingBottom: SPACINGS.sm },
	pb16: { paddingBottom: SPACINGS.md },
	pb24: { paddingBottom: SPACINGS.lg },
	pb32: { paddingBottom: SPACINGS.xl },
	pb48: { paddingBottom: SPACINGS.xxl },

	ph2: { paddingHorizontal: SPACINGS.xxxs },
	ph4: { paddingHorizontal: SPACINGS.xxs },
	ph8: { paddingHorizontal: SPACINGS.xs },
	ph12: { paddingHorizontal: SPACINGS.sm },
	ph16: { paddingHorizontal: SPACINGS.md },
	ph24: { paddingHorizontal: SPACINGS.lg },
	ph32: { paddingHorizontal: SPACINGS.xl },
	ph48: { paddingHorizontal: SPACINGS.xxl },

	pl2: { paddingLeft: SPACINGS.xxxs },
	pl4: { paddingLeft: SPACINGS.xxs },
	pl8: { paddingLeft: SPACINGS.xs },
	pl12: { paddingLeft: SPACINGS.sm },
	pl16: { paddingLeft: SPACINGS.md },
	pl24: { paddingLeft: SPACINGS.lg },
	pl32: { paddingLeft: SPACINGS.xl },
	pl48: { paddingLeft: SPACINGS.xxl },

	pr2: { paddingRight: SPACINGS.xxxs },
	pr4: { paddingRight: SPACINGS.xxs },
	pr8: { paddingRight: SPACINGS.xs },
	pr12: { paddingRight: SPACINGS.sm },
	pr16: { paddingRight: SPACINGS.md },
	pr24: { paddingRight: SPACINGS.lg },
	pr32: { paddingRight: SPACINGS.xl },
	pr48: { paddingRight: SPACINGS.xxl },

	pt2: { paddingTop: SPACINGS.xxxs },
	pt4: { paddingTop: SPACINGS.xxs },
	pt8: { paddingTop: SPACINGS.xs },
	pt12: { paddingTop: SPACINGS.sm },
	pt16: { paddingTop: SPACINGS.md },
	pt24: { paddingTop: SPACINGS.lg },
	pt32: { paddingTop: SPACINGS.xl },
	pt48: { paddingTop: SPACINGS.xxl },

	pv2: { paddingVertical: SPACINGS.xxxs },
	pv4: { paddingVertical: SPACINGS.xxs },
	pv8: { paddingVertical: SPACINGS.xs },
	pv12: { paddingVertical: SPACINGS.sm },
	pv16: { paddingVertical: SPACINGS.md },
	pv24: { paddingVertical: SPACINGS.lg },
	pv32: { paddingVertical: SPACINGS.xl },
	pv48: { paddingVertical: SPACINGS.xxl },
};

export { PADDINGS };
