import { SPACING } from "~/libs/styles/global-styles/spacing";

const PADDINGS = {
	p2: { padding: SPACING.xxxs },
	p4: { padding: SPACING.xxs },
	p8: { padding: SPACING.xs },
	p12: { padding: SPACING.sm },
	p16: { padding: SPACING.md },
	p24: { padding: SPACING.lg },
	p32: { padding: SPACING.xl },
	p48: { padding: SPACING.xxl },

	pb2: { paddingBottom: SPACING.xxxs },
	pb4: { paddingBottom: SPACING.xxs },
	pb8: { paddingBottom: SPACING.xs },
	pb12: { paddingBottom: SPACING.sm },
	pb16: { paddingBottom: SPACING.md },
	pb24: { paddingBottom: SPACING.lg },
	pb32: { paddingBottom: SPACING.xl },
	pb48: { paddingBottom: SPACING.xxl },

	ph2: { paddingHorizontal: SPACING.xxxs },
	ph4: { paddingHorizontal: SPACING.xxs },
	ph8: { paddingHorizontal: SPACING.xs },
	ph12: { paddingHorizontal: SPACING.sm },
	ph16: { paddingHorizontal: SPACING.md },
	ph24: { paddingHorizontal: SPACING.lg },
	ph32: { paddingHorizontal: SPACING.xl },
	ph48: { paddingHorizontal: SPACING.xxl },

	pl2: { paddingLeft: SPACING.xxxs },
	pl4: { paddingLeft: SPACING.xxs },
	pl8: { paddingLeft: SPACING.xs },
	pl12: { paddingLeft: SPACING.sm },
	pl16: { paddingLeft: SPACING.md },
	pl24: { paddingLeft: SPACING.lg },
	pl32: { paddingLeft: SPACING.xl },
	pl48: { paddingLeft: SPACING.xxl },

	pr2: { paddingRight: SPACING.xxxs },
	pr4: { paddingRight: SPACING.xxs },
	pr8: { paddingRight: SPACING.xs },
	pr12: { paddingRight: SPACING.sm },
	pr16: { paddingRight: SPACING.md },
	pr24: { paddingRight: SPACING.lg },
	pr32: { paddingRight: SPACING.xl },
	pr48: { paddingRight: SPACING.xxl },

	pt2: { paddingTop: SPACING.xxxs },
	pt4: { paddingTop: SPACING.xxs },
	pt8: { paddingTop: SPACING.xs },
	pt12: { paddingTop: SPACING.sm },
	pt16: { paddingTop: SPACING.md },
	pt24: { paddingTop: SPACING.lg },
	pt32: { paddingTop: SPACING.xl },
	pt48: { paddingTop: SPACING.xxl },

	pv2: { paddingVertical: SPACING.xxxs },
	pv4: { paddingVertical: SPACING.xxs },
	pv8: { paddingVertical: SPACING.xs },
	pv12: { paddingVertical: SPACING.sm },
	pv16: { paddingVertical: SPACING.md },
	pv24: { paddingVertical: SPACING.lg },
	pv32: { paddingVertical: SPACING.xl },
	pv48: { paddingVertical: SPACING.xxl },
};

export { PADDINGS };
