const DEFAULT_START_TYPING_DELAY = 0;
const FIRST_LETTER_INDEX = 0;
const LETTERS_PRINTED_PER_STEP = 1;
const NEXT_LETTERS_PRINTED_DELAY = 10;

export {
	DEFAULT_START_TYPING_DELAY,
	FIRST_LETTER_INDEX,
	LETTERS_PRINTED_PER_STEP,
	NEXT_LETTERS_PRINTED_DELAY,
};
