const FULL_PROGRESS = 100;

const MIN_SCORE_VALUE = 1;

const RESIZE_EVENT = "resize";

const SLIDER_BACKGROUND_COLOR = "#d9d9d9";

export {
	FULL_PROGRESS,
	MIN_SCORE_VALUE,
	RESIZE_EVENT,
	SLIDER_BACKGROUND_COLOR,
};
