const DRAG_THRESHOLD = 50;

const INITIAL_SLIDE = 0;

const INITIAL_X = 0;

const POSITIVE_MIN_THRESHOLD = 0;

const SINGLE_SLIDE = 1;

const SLIDE_WIDTH_PERCENTAGE = 100;

export {
	DRAG_THRESHOLD,
	INITIAL_SLIDE,
	INITIAL_X,
	POSITIVE_MIN_THRESHOLD,
	SINGLE_SLIDE,
	SLIDE_WIDTH_PERCENTAGE,
};
