type IconName =
	| "aiAssistantAvatar"
	| "aiChatActive"
	| "aiChatInactive"
	| "check"
	| "checkSmall"
	| "clockActive"
	| "clockInactive"
	| "close"
	| "closeSmall"
	| "crossedEye"
	| "error"
	| "eye"
	| "info"
	| "menu"
	| "roundedCheck"
	| "settingsActive"
	| "settingsInactive"
	| "signOut"
	| "success"
	| "tasksActive"
	| "tasksInactive"
	| "upload"
	| "warning"
	| "wheelActive"
	| "wheelInactive";

export { type IconName };
