const IS_DISCARD_BUTTON_DISABLED_INITIAL_VALUE = true;
const AFTER_DISCARD_CHANGES_DELAY = 100;
const IS_RESET_CHANGES_SCORES_INITIAL_VALUE = false;

export {
	AFTER_DISCARD_CHANGES_DELAY,
	IS_DISCARD_BUTTON_DISABLED_INITIAL_VALUE,
	IS_RESET_CHANGES_SCORES_INITIAL_VALUE,
};
