const CHECK_ALL_CATEGORIES_NAME = "All";
const CATEGORIES_FIELD_NAME = "categoryIds";
const CATEGORIES_FORM_DEFAULT_VALUES: number[] = [];

export {
	CATEGORIES_FIELD_NAME,
	CATEGORIES_FORM_DEFAULT_VALUES,
	CHECK_ALL_CATEGORIES_NAME,
};
