name: Continuous Integration Pull Request

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review

  workflow_dispatch:

concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            packages/**/build
          key: ci-pr-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ci-pr-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

  ci-pr:
    permissions:
      contents: read
      pull-requests: write

    name: PR Linting
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Restore Dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            packages/**/build
          key: ci-pr-${{ hashFiles('**/package-lock.json') }}

      - name: Lint Commits
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Lint Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          npx danger ci --failOnErrors --text-only
